import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>GeoBirds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 flex flex-col justify-center items-center gap-4">
        <h1 className="text-4xl">
          GeoBirds
        </h1>
        <h2 className="text-xl">
          Data Visualizer and Editor
        </h2>
        <div className='grid grid-cols-2 gap-2 w-full max-w-[800px]'>
          <Link href={'/orders'}>
            <div className='rounded-lg border-2 border-blue-400 -w-full h-32 flex flex-col justify-start items-center p-2 hover:cursor-pointer'>
              <h2 className='text-xl'>Orders</h2>
            </div>
          </Link>
          <Link href={'/'}>
            <div className='rounded-lg border-2 border-blue-400 -w-full h-32 flex flex-col justify-start items-center p-2 hover:cursor-pointer'>
              <h2 className='text-xl'>Search Species</h2>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link href={'https://github.com/Open-Source-Nature/geobirds'}>
          <a className='hover:underline text-blue-400'>GeoBirds Repository</a>
        </Link>
      </footer>
    </div>
  )
}

export default Home
